CREATE TABLE Users (
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserName NVARCHAR(100) NOT NULL UNIQUE,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Password_Hash NVARCHAR(255) NOT NULL,
	User_Type NVARCHAR(49) NOT NULL,
	Created_Date DATETIME DEFAULT GETDATE(),
	Last_Login DATETIME NULL
);
GO

SELECT * FROM Users;
DROP TABLE Users;